version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_DB: postgres
    ports:
      - 5555:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-networks

  back:
    build: ./back
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    command: /bin/sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"
    networks:
      - app-networks
volumes:
  db-data:
networks:
  app-networks:
